server:
  port: ${SERVER_PORT:8081}

spring:
  profiles:
    active: test
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: ${SHOW_SQL:false}
  security:
    user:
      name: root
      password: root
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/transaction_management${DB_PARAMS:?allowPublicKeyRetrieval=true&useSSL=false}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
